name: Access Secret Example

on:
  push:
    branches:
      - main  # Modify this to match your branch name

jobs:
  access-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'  # Specify your Python version

      - name: Install requests library
        run: pip install requests

      - name: Run Python script
        env:
          APPFOLIO_CLIENT_ID: ${{ secrets.APPFOLIO_CLIENT_ID }}
          APPFOLIO_CLIENT_SECRET: ${{secrets.APPFOLIO_CLIENT_SECRET}}
          APPFOLIO_DATABASE_NAME: ${{secrets.APPFOLIO_DATABASE_NAME}}
        run: 
          python main.py
